
# Application name
spring.application.name=section4-rest-crud-api

# JDBC properties
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# Turn off Spring Boot banner
#spring.main.banner-mode=off

spring.security.user.name = user
spring.security.user.password =test123
