# Application name
spring.application.name=cruddemo

# JDBC properties
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# Turn off Spring Boot banner
spring.main.banner-mode=off

#configure custom path
#springdoc.swagger-ui.path=/my-ui.html

#configure custom path for api docs
#springdoc.api-docs.path=/my-api-docs

